### ISSUE TITLE
Representing meet results

### ISSUE THREAD

**Issue by todorvelichkov** [popov95s/django1#11]
Try to create few endpoints:
1) /meets/ - a page where you can see uploaded meets. (Meet Name, Start Date)
2) /meets/{meet_id}/ - Meet home page where we can see more metadata about the meet: Location, Course, Teams participated, Events.
3) /meets/{meet_id}/{event_id}/ - A page where you can see all results from a meet event: swimmer pos, name, team, time.

**Comment by popov95s** [comment]
I made 3) , but it's just a list of all results. Instead I made a separate /meet/{meet_id} endpoint where all times are posted. 

Last two added meets (that work for sure) have IDs of 178 and 179.

Also made /swimmer/ endpoint for all swimmers with 3 times which gives a href to /swimmer/{swimmer_id}

**Comment by todorvelichkov** [comment]
I made a typo writing the url's. URL's should not be /meets/, /meets//, /meets///, but with different arguments between the forward-slashes. I've updated the first post, check it out.

**Comment by popov95s** [comment]
Finished with this, but could not manage to get the verbose name of event__stroke to display. get_stroke_display did not work in the HTML
