### ISSUE TITLE
Men and Women Team can belong to difference conferences.

### ISSUE THREAD

**Issue by todorvelichkov** [popov95s/django1#4]
With the current model structure, a single `team` can have only one `conference`. But in real-wold teams are divided by `Men Teams` and `Women Teams`, thus they can belong to different conferences.

**Comment by popov95s** [comment]
added gender field to team 

Is there a problem that both Meet and Team have gender fields (is it redundant data ?)

**Comment by todorvelichkov** [comment]
No its not, but meets can be dual genders, so maybe we could add one more option -> (X, Mixed gender).
