### ISSUE TITLE
We should be able to track `event types`

### ISSUE THREAD

**Issue by todorvelichkov** [popov95s/django1#5]
During a `Meet`, a `Swimmer` can `swam` several times in a single `event` (`prelimtime`, `swim-off`, `semifinal`, `finalstime` etc). With the current model structure, we can't tell which time was `prelim`, and which one was not.

**Comment by popov95s** [comment]
added event_type field to Event 

is this where it should go ?

**Comment by todorvelichkov** [comment]
It could work, but I was thinking about adding it into the `Time` model.
Whats the difference? 
If we have an `event_type` in the `Event` class, this will mean that every `time` object will point out to a different `event`. _(50YFree prelims, 50YFree finals, ..., etc.)_
While if `event_type` is inside the `Time` model, then all `Swimmer` times from that `event` will point to a single `event` instance. Thus it would be easier to get all `swimmer`/`swimmers` times from that `Event`

An example:
In the first variant, when `event_type` is inside the `Event` model, one way to get all `50 Y Free` times will look like this?

```
fifty_free_events = Event.objects.filter(event="Free", distance=50, course="SCY")
fifty_free_times = Time.objects.filter(event__in=fifty_free_events)
```

But this is a [`range`](http://dev.mysql.com/doc/refman/5.7/en/range-optimization.html) query (the database should find rows with different `event_id`), which is not impossible, but harder to optimize query.

While if `event_type` is inside the `Time` model, then:

```
fifty_free_event = Event.objects.get(event="Free", distance=50, course="SCY")
fifty_free_times = Time.objects.filter(event=fifty_free_event)
```

this time we have a single value lookup, which can be a lot faster and easier to be optimized.

[Here](https://www.safaribooksonline.com/library/view/high-performance-mysql/0596003064/ch04.html) is something to read about indexes
