### ISSUE TITLE
Import a meet

### ISSUE THREAD

**Issue by todorvelichkov** [popov95s/django1#9]
Try to create a simple meet parser which can read `.cl2` files, then after the meet is parsed import the result using your model architecture. Do not try to match meet/team/swimmers, e.g. if the same files gets uploaded twice, make two different meets with different teams and different swimmers.

**Comment by imanolov** [comment]
There are two dual meets in the attached .zip file. 

[results.zip](https://github.com/popov95s/django1/files/333365/results.zip)

**Comment by imanolov** [comment]
You are also going to need this document. It provides a detailed description about how to read a result file.

[Standard Data Interchange Format.pdf.zip](https://github.com/popov95s/django1/files/333367/Standard.Data.Interchange.Format.pdf.zip)
